project:
  type: website
  output-dir:  docs
  render : 
    - index.qmd
website:
  title: "Weather in Montpellier"
  navbar:
    tools : 
    - icon : github
    href: https://github.com/zakariakhodrium/WeatherMTP 
    text : Github
 

format:
  html:
    theme: lux
    css: styles.css
    toc: true



