project:
  type: website
  output-dir:  docs
  render : 
    - index.qmd
    - about.qmd
website:
  title: "Weather in Montpellier"
  navbar:
    tools : 
    - icon : github
    href: https://github.com/zakariakhodrium/WeatherMTP 
    text : Github
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



